DEBUG:signac.common.config:Reading config file '/home/jacobbieri/repos/persistence-length/signac.rc'.
DEBUG:signac.contrib.project:The project's schema version 1 is supported.
Using environment configuration: Fry
DEBUG:flow.project:Entering buffered mode.
DEBUG:flow.project:Exiting buffered mode.
INFO:flow.project:Executing 1 operation(s) (Pass #01)...
INFO:flow.project:Execute operation 'test2-sim1(32984c2bcf4d53e190defc363c18447b)'...
DEBUG:flow.project:Forking to execute operation 'test2-sim1(32984c2bcf4d53e190defc363c18447b)' with cmd 'python -u /home/jacobbieri/repos/persistence-length/project.py exec test2-sim1 32984c2bcf4d53e190defc363c18447b'.
DEBUG:signac.common.config:Reading config file '/home/jacobbieri/repos/persistence-length/signac.rc'.
DEBUG:signac.contrib.project:The project's schema version 1 is supported.
Using environment configuration: Fry
DEBUG:matplotlib:matplotlib data path: /home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/jacobbieri/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/gmso/core/element.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
INFO:freud.msd:Using SciPy's fftpack for FFTs

Support for writing out LAMMPS data files will be removed
in mbuild 1.0.
See GMSO (https://github.com/mosdef-hub/gmso/tree/main/gmso/formats/lammpsdata) for
continued support for LAMMPS.

DEBUG:matplotlib:CACHEDIR=/home/jacobbieri/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/jacobbieri/.cache/matplotlib/fontlist-v390.json
INFO:numexpr.utils:NumExpr defaulting to 16 threads.
INFO:signac.contrib.job:Enter workspace '/home/jacobbieri/repos/persistence-length/workspace/32984c2bcf4d53e190defc363c18447b'.
JOB ID NUMBER:
32984c2bcf4d53e190defc363c18447b
/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flowermd/base/system.py:659: UserWarning: Units for density were not given, assuming units of g/cm**3.
  warnings.warn(
/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/foyer/forcefield.py:643: UserWarning: Non-atomistic element type detected. Creating custom element for _H5
  warnings.warn(
/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/foyer/forcefield.py:643: UserWarning: Non-atomistic element type detected. Creating custom element for _H3
  warnings.warn(
/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/foyer/forcefield.py:643: UserWarning: Non-atomistic element type detected. Creating custom element for _H4
  warnings.warn(
/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/foyer/forcefield.py:643: UserWarning: Non-atomistic element type detected. Creating custom element for _S2
  warnings.warn(
/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/foyer/forcefield.py:643: UserWarning: Non-atomistic element type detected. Creating custom element for _C0
  warnings.warn(
/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/foyer/forcefield.py:643: UserWarning: Non-atomistic element type detected. Creating custom element for _C1
  warnings.warn(
/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/gmso/core/atom_type.py:198: UserWarning: Masses are assumed to be in units of g/mol
  warnings.warn(UNIT_WARNING_STRING.format("Masses", "g/mol"))
/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/gmso/core/atom_type.py:209: UserWarning: Charges are assumed to be in units of elementary charge
  warnings.warn(
INFO:signac.contrib.job:Leave workspace.
Traceback (most recent call last):
  File "/home/jacobbieri/repos/persistence-length/project.py", line 163, in <module>
    MyProject(environment=Fry).main()
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 5134, in main
    args.func(args)
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 4878, in _main_exec
    operation_function(*aggregate)
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 625, in __call__
    return self._op_func(*jobs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jacobbieri/repos/persistence-length/project.py", line 118, in sample
    system.apply_forcefield(r_cut=2.5, force_field=molff, auto_scale=True,remove_charges=True, remove_hydrogens=True)
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flowermd/base/system.py", line 548, in apply_forcefield
    self.gmso_system = apply(
                       ^^^^^^
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/gmso/parameterization/parameterize.py", line 91, in apply
    parameterizer.run_parameterization()
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/gmso/parameterization/topology_parameterizer.py", line 306, in run_parameterization
    self._set_combining_rule()  # Fail Early if no match
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/gmso/parameterization/topology_parameterizer.py", line 248, in _set_combining_rule
    raise ParameterizationError(
gmso.parameterization.topology_parameterizer.ParameterizationError: Combining rules of the provided forcefields do notmatch, please provide forcefields with same scalingfactors that apply to a Topology
Traceback (most recent call last):
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 3461, in _execute_operation
    subprocess.run(
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python -u /home/jacobbieri/repos/persistence-length/project.py exec test2-sim1 32984c2bcf4d53e190defc363c18447b' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jacobbieri/repos/persistence-length/project.py", line 163, in <module>
    MyProject(environment=Fry).main()
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 5134, in main
    args.func(args)
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 4846, in _main_run
    run()
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 3720, in run
    self._run_operations(
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 3305, in _run_operations
    self._execute_operation(operation, timeout, pretend)
  File "/home/jacobbieri/miniforge3/envs/p_l/lib/python3.11/site-packages/flow/project.py", line 3465, in _execute_operation
    raise UserOperationError(execution_error_message) from error
flow.errors.UserOperationError: An exception was raised during operation test2-sim1 for job or aggregate with id 32984c2bcf4d53e190defc363c18447b.
